// Auto-generated Supabase types placeholder.
// After running the schema migration, generate real types with:
// npx supabase gen types typescript --project-id YOUR_PROJECT_REF > types/database.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          booking_url: string | null;
          booking_provider: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          booking_url?: string | null;
          booking_provider?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          booking_url?: string | null;
          booking_provider?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          organization_id: string | null;
          first_name: string | null;
          last_name: string | null;
          email: string;
          phone: string | null;
          job_title: string | null;
          avatar_url: string | null;
          role: string;
          timezone: string;
          date_format: string;
          time_format: string;
          language: string;
          notification_preferences: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          organization_id?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          email: string;
          phone?: string | null;
          job_title?: string | null;
          avatar_url?: string | null;
          role?: string;
          timezone?: string;
          date_format?: string;
          time_format?: string;
          language?: string;
          notification_preferences?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          organization_id?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          email?: string;
          phone?: string | null;
          job_title?: string | null;
          avatar_url?: string | null;
          role?: string;
          timezone?: string;
          date_format?: string;
          time_format?: string;
          language?: string;
          notification_preferences?: Json;
          updated_at?: string;
        };
        Relationships: [];
      };
      customers: {
        Row: {
          id: string;
          organization_id: string;
          created_by: string | null;
          first_name: string;
          last_name: string;
          email: string;
          phone: string | null;
          avatar_url: string | null;
          status: Database["public"]["Enums"]["customer_status"];
          plan: Database["public"]["Enums"]["customer_plan"];
          mrr: number;
          health_score: number;
          lifetime_value: number;
          tenure: number;
          last_contact: string | null;
          company: string | null;
          job_title: string | null;
          industry: string | null;
          company_size: string | null;
          website: string | null;
          street_address: string | null;
          city: string | null;
          state: string | null;
          postal_code: string | null;
          country: string;
          timezone: string | null;
          customer_since: string | null;
          renewal_date: string | null;
          tags: string[];
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          created_by?: string | null;
          first_name: string;
          last_name: string;
          email: string;
          phone?: string | null;
          avatar_url?: string | null;
          status?: Database["public"]["Enums"]["customer_status"];
          plan?: Database["public"]["Enums"]["customer_plan"];
          mrr?: number;
          health_score?: number;
          lifetime_value?: number;
          tenure?: number;
          last_contact?: string | null;
          company?: string | null;
          job_title?: string | null;
          industry?: string | null;
          company_size?: string | null;
          website?: string | null;
          street_address?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          country?: string;
          timezone?: string | null;
          customer_since?: string | null;
          renewal_date?: string | null;
          tags?: string[];
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string | null;
          avatar_url?: string | null;
          status?: Database["public"]["Enums"]["customer_status"];
          plan?: Database["public"]["Enums"]["customer_plan"];
          mrr?: number;
          health_score?: number;
          lifetime_value?: number;
          tenure?: number;
          last_contact?: string | null;
          company?: string | null;
          job_title?: string | null;
          industry?: string | null;
          company_size?: string | null;
          website?: string | null;
          street_address?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          country?: string;
          timezone?: string | null;
          customer_since?: string | null;
          renewal_date?: string | null;
          tags?: string[];
          notes?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      customer_notes: {
        Row: {
          id: string;
          customer_id: string;
          author_id: string | null;
          author_name: string;
          content: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          customer_id: string;
          author_id?: string | null;
          author_name: string;
          content: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          content?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      customer_activities: {
        Row: {
          id: string;
          customer_id: string;
          type: string;
          title: string;
          description: string | null;
          badge_label: string | null;
          badge_variant: string | null;
          meta: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          customer_id: string;
          type: string;
          title: string;
          description?: string | null;
          badge_label?: string | null;
          badge_variant?: string | null;
          meta?: string | null;
          created_at?: string;
        };
        Update: {
          type?: string;
          title?: string;
          description?: string | null;
          badge_label?: string | null;
          badge_variant?: string | null;
          meta?: string | null;
        };
        Relationships: [];
      };
      customer_custom_fields: {
        Row: {
          id: string;
          customer_id: string;
          name: string;
          value: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          customer_id: string;
          name: string;
          value?: string | null;
          created_at?: string;
        };
        Update: {
          name?: string;
          value?: string | null;
        };
        Relationships: [];
      };
      leads: {
        Row: {
          id: string;
          organization_id: string;
          created_by: string | null;
          name: string;
          email: string;
          company: string | null;
          phone: string | null;
          linkedin: string | null;
          location: string | null;
          employees: string | null;
          website: string | null;
          industry: string | null;
          status: Database["public"]["Enums"]["lead_status"];
          source: Database["public"]["Enums"]["lead_source"];
          estimated_value: number;
          score: number;
          win_probability: number;
          days_in_pipeline: number;
          score_breakdown: Json | null;
          last_scored_at: string | null;
          engagement_score: number;
          icp_match_score: number | null;
          icp_profile_id: string | null;
          icp_match_breakdown: Json | null;
          qualification_data: Json | null;
          qualification_grade: string | null;
          qualification_score: number | null;
          twitter: string | null;
          facebook: string | null;
          instagram: string | null;
          title: string | null;
          next_followup: string | null;
          followup_note: string | null;
          pain_points: string | null;
          trigger_event: string | null;
          timezone: string | null;
          preferred_language: string | null;
          last_contacted_at: string | null;
          tags: string[] | null;
          revenue_range: string | null;
          tech_stack: string | null;
          funding_stage: string | null;
          decision_role: string | null;
          current_solution: string | null;
          referred_by: string | null;
          personal_note: string | null;
          birthday: string | null;
          content_interests: string[] | null;
          meeting_preference: string | null;
          assistant_name: string | null;
          assistant_email: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          created_by?: string | null;
          name: string;
          email: string;
          company?: string | null;
          phone?: string | null;
          linkedin?: string | null;
          location?: string | null;
          employees?: string | null;
          website?: string | null;
          industry?: string | null;
          status?: Database["public"]["Enums"]["lead_status"];
          source?: Database["public"]["Enums"]["lead_source"];
          estimated_value?: number;
          score?: number;
          win_probability?: number;
          days_in_pipeline?: number;
          score_breakdown?: Json | null;
          last_scored_at?: string | null;
          engagement_score?: number;
          icp_match_score?: number | null;
          icp_profile_id?: string | null;
          icp_match_breakdown?: Json | null;
          qualification_data?: Json | null;
          qualification_grade?: string | null;
          qualification_score?: number | null;
          twitter?: string | null;
          facebook?: string | null;
          instagram?: string | null;
          title?: string | null;
          next_followup?: string | null;
          followup_note?: string | null;
          pain_points?: string | null;
          trigger_event?: string | null;
          timezone?: string | null;
          preferred_language?: string | null;
          last_contacted_at?: string | null;
          tags?: string[] | null;
          revenue_range?: string | null;
          tech_stack?: string | null;
          funding_stage?: string | null;
          decision_role?: string | null;
          current_solution?: string | null;
          referred_by?: string | null;
          personal_note?: string | null;
          birthday?: string | null;
          content_interests?: string[] | null;
          meeting_preference?: string | null;
          assistant_name?: string | null;
          assistant_email?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          email?: string;
          company?: string | null;
          phone?: string | null;
          linkedin?: string | null;
          location?: string | null;
          employees?: string | null;
          website?: string | null;
          industry?: string | null;
          status?: Database["public"]["Enums"]["lead_status"];
          source?: Database["public"]["Enums"]["lead_source"];
          estimated_value?: number;
          score?: number;
          win_probability?: number;
          days_in_pipeline?: number;
          score_breakdown?: Json | null;
          last_scored_at?: string | null;
          engagement_score?: number;
          icp_match_score?: number | null;
          icp_profile_id?: string | null;
          icp_match_breakdown?: Json | null;
          qualification_data?: Json | null;
          qualification_grade?: string | null;
          qualification_score?: number | null;
          twitter?: string | null;
          facebook?: string | null;
          instagram?: string | null;
          title?: string | null;
          next_followup?: string | null;
          followup_note?: string | null;
          pain_points?: string | null;
          trigger_event?: string | null;
          timezone?: string | null;
          preferred_language?: string | null;
          last_contacted_at?: string | null;
          tags?: string[] | null;
          revenue_range?: string | null;
          tech_stack?: string | null;
          funding_stage?: string | null;
          decision_role?: string | null;
          current_solution?: string | null;
          referred_by?: string | null;
          personal_note?: string | null;
          birthday?: string | null;
          content_interests?: string[] | null;
          meeting_preference?: string | null;
          assistant_name?: string | null;
          assistant_email?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      lead_notes: {
        Row: {
          id: string;
          lead_id: string;
          author_id: string | null;
          author_name: string;
          content: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          lead_id: string;
          author_id?: string | null;
          author_name: string;
          content: string;
          created_at?: string;
        };
        Update: {
          content?: string;
        };
        Relationships: [];
      };
      lead_activities: {
        Row: {
          id: string;
          lead_id: string;
          type: string;
          title: string;
          description: string | null;
          badge_label: string | null;
          badge_variant: string | null;
          meta: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          lead_id: string;
          type: string;
          title: string;
          description?: string | null;
          badge_label?: string | null;
          badge_variant?: string | null;
          meta?: string | null;
          created_at?: string;
        };
        Update: {
          type?: string;
          title?: string;
          description?: string | null;
        };
        Relationships: [];
      };
      deals: {
        Row: {
          id: string;
          organization_id: string;
          created_by: string | null;
          customer_id: string | null;
          name: string;
          company: string | null;
          value: number;
          probability: number;
          stage: Database["public"]["Enums"]["deal_stage"];
          close_date: string | null;
          owner_id: string | null;
          days_in_stage: number;
          days_to_close: number;
          last_activity: string | null;
          contact_name: string | null;
          contact_email: string | null;
          contact_avatar: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          created_by?: string | null;
          customer_id?: string | null;
          name: string;
          company?: string | null;
          value?: number;
          probability?: number;
          stage?: Database["public"]["Enums"]["deal_stage"];
          close_date?: string | null;
          owner_id?: string | null;
          days_in_stage?: number;
          days_to_close?: number;
          last_activity?: string | null;
          contact_name?: string | null;
          contact_email?: string | null;
          contact_avatar?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          customer_id?: string | null;
          name?: string;
          company?: string | null;
          value?: number;
          probability?: number;
          stage?: Database["public"]["Enums"]["deal_stage"];
          close_date?: string | null;
          owner_id?: string | null;
          days_in_stage?: number;
          days_to_close?: number;
          last_activity?: string | null;
          contact_name?: string | null;
          contact_email?: string | null;
          contact_avatar?: string | null;
          notes?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      deal_notes: {
        Row: {
          id: string;
          deal_id: string;
          author_id: string | null;
          author_name: string;
          content: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          deal_id: string;
          author_id?: string | null;
          author_name: string;
          content: string;
          created_at?: string;
        };
        Update: {
          content?: string;
        };
        Relationships: [];
      };
      deal_activities: {
        Row: {
          id: string;
          deal_id: string;
          type: string;
          title: string;
          description: string | null;
          badge_label: string | null;
          badge_variant: string | null;
          meta: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          deal_id: string;
          type: string;
          title: string;
          description?: string | null;
          badge_label?: string | null;
          badge_variant?: string | null;
          meta?: string | null;
          created_at?: string;
        };
        Update: {
          type?: string;
          title?: string;
          description?: string | null;
        };
        Relationships: [];
      };
      activities: {
        Row: {
          id: string;
          organization_id: string;
          created_by: string | null;
          type: Database["public"]["Enums"]["activity_type"];
          title: string;
          description: string | null;
          status: Database["public"]["Enums"]["activity_status"];
          date: string | null;
          time: string | null;
          assignee: string | null;
          related_type: Database["public"]["Enums"]["related_entity_type"] | null;
          related_name: string | null;
          related_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          created_by?: string | null;
          type: Database["public"]["Enums"]["activity_type"];
          title: string;
          description?: string | null;
          status?: Database["public"]["Enums"]["activity_status"];
          date?: string | null;
          time?: string | null;
          assignee?: string | null;
          related_type?: Database["public"]["Enums"]["related_entity_type"] | null;
          related_name?: string | null;
          related_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          type?: Database["public"]["Enums"]["activity_type"];
          title?: string;
          description?: string | null;
          status?: Database["public"]["Enums"]["activity_status"];
          date?: string | null;
          time?: string | null;
          assignee?: string | null;
          related_type?: Database["public"]["Enums"]["related_entity_type"] | null;
          related_name?: string | null;
          related_id?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      calendar_events: {
        Row: {
          id: string;
          organization_id: string;
          created_by: string | null;
          title: string;
          description: string | null;
          date: string;
          start_time: string | null;
          end_time: string | null;
          type: string;
          status: string;
          related_type: Database["public"]["Enums"]["related_entity_type"] | null;
          related_name: string | null;
          related_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          created_by?: string | null;
          title: string;
          description?: string | null;
          date: string;
          start_time?: string | null;
          end_time?: string | null;
          type?: string;
          status?: string;
          related_type?: Database["public"]["Enums"]["related_entity_type"] | null;
          related_name?: string | null;
          related_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          title?: string;
          description?: string | null;
          date?: string;
          start_time?: string | null;
          end_time?: string | null;
          type?: string;
          status?: string;
          related_type?: Database["public"]["Enums"]["related_entity_type"] | null;
          related_name?: string | null;
          related_id?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      scoring_profiles: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          weight_company_size: number;
          weight_industry_fit: number;
          weight_engagement: number;
          weight_source_quality: number;
          weight_budget: number;
          target_industries: string[];
          target_company_sizes: string[];
          source_rankings: Json;
          is_default: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name?: string;
          weight_company_size?: number;
          weight_industry_fit?: number;
          weight_engagement?: number;
          weight_source_quality?: number;
          weight_budget?: number;
          target_industries?: string[];
          target_company_sizes?: string[];
          source_rankings?: Json;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          weight_company_size?: number;
          weight_industry_fit?: number;
          weight_engagement?: number;
          weight_source_quality?: number;
          weight_budget?: number;
          target_industries?: string[];
          target_company_sizes?: string[];
          source_rankings?: Json;
          is_default?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      lead_score_history: {
        Row: {
          id: string;
          lead_id: string;
          score: number;
          breakdown: Json;
          scored_at: string;
        };
        Insert: {
          id?: string;
          lead_id: string;
          score: number;
          breakdown?: Json;
          scored_at?: string;
        };
        Update: {
          score?: number;
          breakdown?: Json;
        };
        Relationships: [];
      };
      icp_profiles: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          description: string | null;
          criteria: Json;
          weights: Json;
          buyer_personas: Json;
          color: string | null;
          is_primary: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          description?: string | null;
          criteria?: Json;
          weights?: Json;
          buyer_personas?: Json;
          color?: string | null;
          is_primary?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          description?: string | null;
          criteria?: Json;
          weights?: Json;
          buyer_personas?: Json;
          color?: string | null;
          is_primary?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      sequences: {
        Row: {
          id: string;
          organization_id: string;
          created_by: string | null;
          name: string;
          description: string | null;
          status: Database["public"]["Enums"]["sequence_status"];
          category: string;
          total_steps: number;
          total_enrolled: number;
          reply_rate: number;
          total_sent: number;
          total_opened: number;
          total_clicked: number;
          total_replied: number;
          total_bounced: number;
          open_rate: number;
          click_rate: number;
          settings: Json;
          schedule_timezone: string;
          schedule_windows: Json;
          daily_send_limit: number;
          sent_today: number;
          priority: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          created_by?: string | null;
          name: string;
          description?: string | null;
          status?: Database["public"]["Enums"]["sequence_status"];
          category?: string;
          total_steps?: number;
          total_enrolled?: number;
          reply_rate?: number;
          total_sent?: number;
          total_opened?: number;
          total_clicked?: number;
          total_replied?: number;
          total_bounced?: number;
          open_rate?: number;
          click_rate?: number;
          settings?: Json;
          schedule_timezone?: string;
          schedule_windows?: Json;
          daily_send_limit?: number;
          sent_today?: number;
          priority?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          description?: string | null;
          status?: Database["public"]["Enums"]["sequence_status"];
          category?: string;
          total_steps?: number;
          total_enrolled?: number;
          reply_rate?: number;
          total_sent?: number;
          total_opened?: number;
          total_clicked?: number;
          total_replied?: number;
          total_bounced?: number;
          open_rate?: number;
          click_rate?: number;
          settings?: Json;
          schedule_timezone?: string;
          schedule_windows?: Json;
          daily_send_limit?: number;
          sent_today?: number;
          priority?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      sequence_steps: {
        Row: {
          id: string;
          sequence_id: string;
          step_order: number;
          step_type: string;
          delay_days: number;
          subject: string | null;
          body: string | null;
          channel: string | null;
          channel_config: Json;
          variants: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          sequence_id: string;
          step_order?: number;
          step_type?: string;
          delay_days?: number;
          subject?: string | null;
          body?: string | null;
          channel?: string | null;
          channel_config?: Json;
          variants?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          step_order?: number;
          step_type?: string;
          delay_days?: number;
          subject?: string | null;
          body?: string | null;
          channel?: string | null;
          channel_config?: Json;
          variants?: Json;
          updated_at?: string;
        };
        Relationships: [];
      };
      email_templates: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          subject: string;
          body: string;
          category: string;
          merge_fields: string[];
          usage_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          subject: string;
          body: string;
          category?: string;
          merge_fields?: string[];
          usage_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          subject?: string;
          body?: string;
          category?: string;
          merge_fields?: string[];
          usage_count?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      sequence_enrollments: {
        Row: {
          id: string;
          sequence_id: string;
          lead_id: string;
          current_step: number;
          status: Database["public"]["Enums"]["enrollment_status"];
          enrolled_at: string;
          completed_at: string | null;
          paused_at: string | null;
          whatsapp_account_id: string | null;
          linkedin_account_id: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          sequence_id: string;
          lead_id: string;
          current_step?: number;
          status?: Database["public"]["Enums"]["enrollment_status"];
          enrolled_at?: string;
          completed_at?: string | null;
          paused_at?: string | null;
          whatsapp_account_id?: string | null;
          linkedin_account_id?: string | null;
          updated_at?: string;
        };
        Update: {
          current_step?: number;
          status?: Database["public"]["Enums"]["enrollment_status"];
          completed_at?: string | null;
          paused_at?: string | null;
          whatsapp_account_id?: string | null;
          linkedin_account_id?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      sequence_events: {
        Row: {
          id: string;
          enrollment_id: string;
          step_id: string | null;
          event_type: string;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          enrollment_id: string;
          step_id?: string | null;
          event_type: string;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          event_type?: string;
          metadata?: Json;
        };
        Relationships: [];
      };
      competitors: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          website: string | null;
          category: string;
          description: string | null;
          strengths: string[];
          weaknesses: string[];
          pricing: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          website?: string | null;
          category?: string;
          description?: string | null;
          strengths?: string[];
          weaknesses?: string[];
          pricing?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          website?: string | null;
          category?: string;
          description?: string | null;
          strengths?: string[];
          weaknesses?: string[];
          pricing?: Json;
          updated_at?: string;
        };
        Relationships: [];
      };
      battle_cards: {
        Row: {
          id: string;
          competitor_id: string;
          their_strengths: string[];
          their_weaknesses: string[];
          our_advantages: string[];
          switching_costs: Json;
          switching_triggers: string[];
          landmine_questions: string[];
          positioning_statement: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          competitor_id: string;
          their_strengths?: string[];
          their_weaknesses?: string[];
          our_advantages?: string[];
          switching_costs?: Json;
          switching_triggers?: string[];
          landmine_questions?: string[];
          positioning_statement?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          their_strengths?: string[];
          their_weaknesses?: string[];
          our_advantages?: string[];
          switching_costs?: Json;
          switching_triggers?: string[];
          landmine_questions?: string[];
          positioning_statement?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      lead_competitors: {
        Row: {
          id: string;
          lead_id: string;
          competitor_id: string;
          confidence: string;
          evidence: string | null;
          detected_at: string;
        };
        Insert: {
          id?: string;
          lead_id: string;
          competitor_id: string;
          confidence?: string;
          evidence?: string | null;
          detected_at?: string;
        };
        Update: {
          confidence?: string;
          evidence?: string | null;
        };
        Relationships: [];
      };
      objection_playbook: {
        Row: {
          id: string;
          organization_id: string;
          category: string;
          objection_text: string;
          hidden_meaning: string | null;
          ffr_response: string | null;
          abc_response: string | null;
          follow_up_question: string | null;
          proof_point: string | null;
          walk_away_criteria: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          category?: string;
          objection_text: string;
          hidden_meaning?: string | null;
          ffr_response?: string | null;
          abc_response?: string | null;
          follow_up_question?: string | null;
          proof_point?: string | null;
          walk_away_criteria?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          category?: string;
          objection_text?: string;
          hidden_meaning?: string | null;
          ffr_response?: string | null;
          abc_response?: string | null;
          follow_up_question?: string | null;
          proof_point?: string | null;
          walk_away_criteria?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      proposals: {
        Row: {
          id: string;
          organization_id: string;
          deal_id: string | null;
          title: string;
          status: string;
          content: Json;
          pricing_tiers: Json;
          valid_until: string | null;
          sent_at: string | null;
          viewed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          deal_id?: string | null;
          title: string;
          status?: string;
          content?: Json;
          pricing_tiers?: Json;
          valid_until?: string | null;
          sent_at?: string | null;
          viewed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          deal_id?: string | null;
          title?: string;
          status?: string;
          content?: Json;
          pricing_tiers?: Json;
          valid_until?: string | null;
          sent_at?: string | null;
          viewed_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      contacts: {
        Row: {
          id: string;
          organization_id: string;
          lead_id: string | null;
          customer_id: string | null;
          name: string;
          title: string | null;
          email: string | null;
          phone: string | null;
          linkedin: string | null;
          buying_role: string;
          influence_level: string;
          personalization_anchors: Json;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          lead_id?: string | null;
          customer_id?: string | null;
          name: string;
          title?: string | null;
          email?: string | null;
          phone?: string | null;
          linkedin?: string | null;
          buying_role?: string;
          influence_level?: string;
          personalization_anchors?: Json;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          lead_id?: string | null;
          customer_id?: string | null;
          name?: string;
          title?: string | null;
          email?: string | null;
          phone?: string | null;
          linkedin?: string | null;
          buying_role?: string;
          influence_level?: string;
          personalization_anchors?: Json;
          notes?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      copy_templates: {
        Row: {
          id: string;
          organization_id: string;
          category: string;
          name: string;
          headline: string | null;
          body: string | null;
          cta: string | null;
          tags: string[];
          usage_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          category?: string;
          name: string;
          headline?: string | null;
          body?: string | null;
          cta?: string | null;
          tags?: string[];
          usage_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          category?: string;
          name?: string;
          headline?: string | null;
          body?: string | null;
          cta?: string | null;
          tags?: string[];
          usage_count?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      user_integrations: {
        Row: {
          id: string;
          user_id: string;
          integration_name: string;
          connected: boolean;
          config: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          integration_name: string;
          connected?: boolean;
          config?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          connected?: boolean;
          config?: Json;
          updated_at?: string;
        };
        Relationships: [];
      };
      ai_settings: {
        Row: {
          id: string;
          organization_id: string;
          api_key: string | null;
          apify_api_key: string | null;
          default_model: string;
          feature_lead_scoring: boolean;
          feature_icp_matching: boolean;
          feature_outreach: boolean;
          feature_proposals: boolean;
          feature_meetings: boolean;
          feature_analytics: boolean;
          feature_competitors: boolean;
          feature_objections: boolean;
          feature_chat: boolean;
          autonomy_lead_scoring: string;
          autonomy_icp_matching: string;
          autonomy_outreach: string;
          autonomy_proposals: string;
          autonomy_meetings: string;
          autonomy_analytics: string;
          autonomy_competitors: string;
          autonomy_objections: string;
          tokens_used_today: number;
          tokens_used_month: number;
          daily_token_limit: number;
          monthly_token_limit: number;
          last_token_reset_daily: string;
          last_token_reset_monthly: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          api_key?: string | null;
          apify_api_key?: string | null;
          default_model?: string;
          feature_lead_scoring?: boolean;
          feature_icp_matching?: boolean;
          feature_outreach?: boolean;
          feature_proposals?: boolean;
          feature_meetings?: boolean;
          feature_analytics?: boolean;
          feature_competitors?: boolean;
          feature_objections?: boolean;
          feature_chat?: boolean;
          autonomy_lead_scoring?: string;
          autonomy_icp_matching?: string;
          autonomy_outreach?: string;
          autonomy_proposals?: string;
          autonomy_meetings?: string;
          autonomy_analytics?: string;
          autonomy_competitors?: string;
          autonomy_objections?: string;
          tokens_used_today?: number;
          tokens_used_month?: number;
          daily_token_limit?: number;
          monthly_token_limit?: number;
          last_token_reset_daily?: string;
          last_token_reset_monthly?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          api_key?: string | null;
          apify_api_key?: string | null;
          default_model?: string;
          feature_lead_scoring?: boolean;
          feature_icp_matching?: boolean;
          feature_outreach?: boolean;
          feature_proposals?: boolean;
          feature_meetings?: boolean;
          feature_analytics?: boolean;
          feature_competitors?: boolean;
          feature_objections?: boolean;
          feature_chat?: boolean;
          autonomy_lead_scoring?: string;
          autonomy_icp_matching?: string;
          autonomy_outreach?: string;
          autonomy_proposals?: string;
          autonomy_meetings?: string;
          autonomy_analytics?: string;
          autonomy_competitors?: string;
          autonomy_objections?: string;
          tokens_used_today?: number;
          tokens_used_month?: number;
          daily_token_limit?: number;
          monthly_token_limit?: number;
          last_token_reset_daily?: string;
          last_token_reset_monthly?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      ai_usage_log: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string;
          feature: string;
          model: string;
          input_tokens: number;
          output_tokens: number;
          total_tokens: number;
          duration_ms: number;
          success: boolean;
          error_message: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          user_id: string;
          feature: string;
          model: string;
          input_tokens?: number;
          output_tokens?: number;
          total_tokens?: number;
          duration_ms?: number;
          success?: boolean;
          error_message?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          feature?: string;
          model?: string;
          input_tokens?: number;
          output_tokens?: number;
          total_tokens?: number;
          duration_ms?: number;
          success?: boolean;
          error_message?: string | null;
          metadata?: Json;
        };
        Relationships: [];
      };
      // ── Email System Tables ──────────────────────────────────────────────
      email_accounts: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string;
          provider: Database["public"]["Enums"]["email_provider"];
          email_address: string;
          display_name: string | null;
          status: Database["public"]["Enums"]["email_account_status"];
          oauth_tokens: Json | null;
          imap_config: Json | null;
          smtp_config: Json | null;
          daily_send_limit: number;
          daily_sent_count: number;
          warmup_enabled: boolean;
          warmup_limit: number;
          reputation_score: number;
          last_sent_at: string | null;
          last_synced_at: string | null;
          last_error: string | null;
          signature_html: string | null;
          is_default: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          user_id: string;
          provider: Database["public"]["Enums"]["email_provider"];
          email_address: string;
          display_name?: string | null;
          status?: Database["public"]["Enums"]["email_account_status"];
          oauth_tokens?: Json | null;
          imap_config?: Json | null;
          smtp_config?: Json | null;
          daily_send_limit?: number;
          daily_sent_count?: number;
          warmup_enabled?: boolean;
          warmup_limit?: number;
          reputation_score?: number;
          last_sent_at?: string | null;
          last_synced_at?: string | null;
          last_error?: string | null;
          signature_html?: string | null;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          provider?: Database["public"]["Enums"]["email_provider"];
          email_address?: string;
          display_name?: string | null;
          status?: Database["public"]["Enums"]["email_account_status"];
          oauth_tokens?: Json | null;
          imap_config?: Json | null;
          smtp_config?: Json | null;
          daily_send_limit?: number;
          daily_sent_count?: number;
          warmup_enabled?: boolean;
          warmup_limit?: number;
          reputation_score?: number;
          last_sent_at?: string | null;
          last_synced_at?: string | null;
          last_error?: string | null;
          signature_html?: string | null;
          is_default?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      email_threads: {
        Row: {
          id: string;
          organization_id: string;
          email_account_id: string;
          lead_id: string | null;
          contact_id: string | null;
          customer_id: string | null;
          subject: string;
          snippet: string | null;
          last_message_at: string;
          message_count: number;
          is_read: boolean;
          is_starred: boolean;
          is_archived: boolean;
          enrollment_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          email_account_id: string;
          lead_id?: string | null;
          contact_id?: string | null;
          customer_id?: string | null;
          subject?: string;
          snippet?: string | null;
          last_message_at?: string;
          message_count?: number;
          is_read?: boolean;
          is_starred?: boolean;
          is_archived?: boolean;
          enrollment_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          email_account_id?: string;
          lead_id?: string | null;
          contact_id?: string | null;
          customer_id?: string | null;
          subject?: string;
          snippet?: string | null;
          last_message_at?: string;
          message_count?: number;
          is_read?: boolean;
          is_starred?: boolean;
          is_archived?: boolean;
          enrollment_id?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      email_messages: {
        Row: {
          id: string;
          organization_id: string;
          thread_id: string;
          email_account_id: string;
          from_address: string;
          to_addresses: string[];
          cc_addresses: string[];
          bcc_addresses: string[];
          reply_to: string | null;
          subject: string;
          body_html: string;
          body_text: string | null;
          direction: Database["public"]["Enums"]["email_direction"];
          status: Database["public"]["Enums"]["email_message_status"];
          provider_message_id: string | null;
          message_id_header: string | null;
          in_reply_to: string | null;
          references_header: string | null;
          tracking_pixel_id: string | null;
          open_count: number;
          click_count: number;
          first_opened_at: string | null;
          last_opened_at: string | null;
          enrollment_id: string | null;
          step_id: string | null;
          error_message: string | null;
          bounce_type: string | null;
          scheduled_at: string | null;
          sent_at: string | null;
          received_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          thread_id: string;
          email_account_id: string;
          from_address: string;
          to_addresses: string[];
          cc_addresses?: string[];
          bcc_addresses?: string[];
          reply_to?: string | null;
          subject?: string;
          body_html?: string;
          body_text?: string | null;
          direction: Database["public"]["Enums"]["email_direction"];
          status?: Database["public"]["Enums"]["email_message_status"];
          provider_message_id?: string | null;
          message_id_header?: string | null;
          in_reply_to?: string | null;
          references_header?: string | null;
          tracking_pixel_id?: string | null;
          open_count?: number;
          click_count?: number;
          first_opened_at?: string | null;
          last_opened_at?: string | null;
          enrollment_id?: string | null;
          step_id?: string | null;
          error_message?: string | null;
          bounce_type?: string | null;
          scheduled_at?: string | null;
          sent_at?: string | null;
          received_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          thread_id?: string;
          email_account_id?: string;
          from_address?: string;
          to_addresses?: string[];
          cc_addresses?: string[];
          bcc_addresses?: string[];
          reply_to?: string | null;
          subject?: string;
          body_html?: string;
          body_text?: string | null;
          direction?: Database["public"]["Enums"]["email_direction"];
          status?: Database["public"]["Enums"]["email_message_status"];
          provider_message_id?: string | null;
          message_id_header?: string | null;
          in_reply_to?: string | null;
          references_header?: string | null;
          tracking_pixel_id?: string | null;
          open_count?: number;
          click_count?: number;
          first_opened_at?: string | null;
          last_opened_at?: string | null;
          enrollment_id?: string | null;
          step_id?: string | null;
          error_message?: string | null;
          bounce_type?: string | null;
          scheduled_at?: string | null;
          sent_at?: string | null;
          received_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      email_tracking_events: {
        Row: {
          id: string;
          message_id: string;
          event_type: Database["public"]["Enums"]["tracking_event_type"];
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          message_id: string;
          event_type: Database["public"]["Enums"]["tracking_event_type"];
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          event_type?: Database["public"]["Enums"]["tracking_event_type"];
          metadata?: Json;
        };
        Relationships: [];
      };
      email_link_tracking: {
        Row: {
          id: string;
          message_id: string;
          original_url: string;
          tracking_url: string;
          click_count: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          message_id: string;
          original_url: string;
          tracking_url: string;
          click_count?: number;
          created_at?: string;
        };
        Update: {
          original_url?: string;
          tracking_url?: string;
          click_count?: number;
        };
        Relationships: [];
      };
      campaign_tags: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          color: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          color?: string;
          created_at?: string;
        };
        Update: {
          name?: string;
          color?: string;
        };
        Relationships: [];
      };
      sequence_tags: {
        Row: {
          sequence_id: string;
          tag_id: string;
        };
        Insert: {
          sequence_id: string;
          tag_id: string;
        };
        Update: {
          sequence_id?: string;
          tag_id?: string;
        };
        Relationships: [];
      };
      sequence_email_accounts: {
        Row: {
          sequence_id: string;
          email_account_id: string;
        };
        Insert: {
          sequence_id: string;
          email_account_id: string;
        };
        Update: {
          sequence_id?: string;
          email_account_id?: string;
        };
        Relationships: [];
      };
      lead_searches: {
        Row: {
          id: string;
          organization_id: string;
          created_by: string | null;
          name: string;
          filters: Json;
          result_count: number;
          last_run_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          created_by?: string | null;
          name: string;
          filters?: Json;
          result_count?: number;
          last_run_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          filters?: Json;
          result_count?: number;
          last_run_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      scraped_leads: {
        Row: {
          id: string;
          organization_id: string;
          search_id: string | null;
          first_name: string | null;
          last_name: string | null;
          email: string | null;
          title: string | null;
          company: string | null;
          industry: string | null;
          location: string | null;
          linkedin_url: string | null;
          company_website: string | null;
          company_size: string | null;
          phone: string | null;
          verified: boolean;
          imported: boolean;
          imported_lead_id: string | null;
          source: string;
          metadata: Json;
          icp_match_score: number | null;
          ai_quality_score: number | null;
          verification_status: string;
          verified_at: string | null;
          duplicate_of: string | null;
          confidence_score: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          search_id?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          email?: string | null;
          title?: string | null;
          company?: string | null;
          industry?: string | null;
          location?: string | null;
          linkedin_url?: string | null;
          company_website?: string | null;
          company_size?: string | null;
          phone?: string | null;
          verified?: boolean;
          imported?: boolean;
          imported_lead_id?: string | null;
          source?: string;
          metadata?: Json;
          icp_match_score?: number | null;
          ai_quality_score?: number | null;
          verification_status?: string;
          verified_at?: string | null;
          duplicate_of?: string | null;
          confidence_score?: number;
          created_at?: string;
        };
        Update: {
          search_id?: string | null;
          first_name?: string | null;
          last_name?: string | null;
          email?: string | null;
          title?: string | null;
          company?: string | null;
          industry?: string | null;
          location?: string | null;
          linkedin_url?: string | null;
          company_website?: string | null;
          company_size?: string | null;
          phone?: string | null;
          verified?: boolean;
          imported?: boolean;
          imported_lead_id?: string | null;
          source?: string;
          metadata?: Json;
          icp_match_score?: number | null;
          ai_quality_score?: number | null;
          verification_status?: string;
          verified_at?: string | null;
          duplicate_of?: string | null;
          confidence_score?: number;
        };
        Relationships: [];
      };
      apify_scraper_runs: {
        Row: {
          id: string;
          organization_id: string;
          search_id: string | null;
          created_by: string | null;
          actor_id: string;
          source: string;
          input_params: Json;
          status: string;
          apify_run_id: string | null;
          apify_dataset_id: string | null;
          result_count: number;
          error_message: string | null;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          search_id?: string | null;
          created_by?: string | null;
          actor_id: string;
          source: string;
          input_params?: Json;
          status?: string;
          apify_run_id?: string | null;
          apify_dataset_id?: string | null;
          result_count?: number;
          error_message?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
        Update: {
          search_id?: string | null;
          actor_id?: string;
          source?: string;
          input_params?: Json;
          status?: string;
          apify_run_id?: string | null;
          apify_dataset_id?: string | null;
          result_count?: number;
          error_message?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
        };
        Relationships: [];
      };
      copilot_conversations: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string;
          title: string;
          summary: string | null;
          is_pinned: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          user_id: string;
          title?: string;
          summary?: string | null;
          is_pinned?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          title?: string;
          summary?: string | null;
          is_pinned?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      copilot_messages: {
        Row: {
          id: string;
          conversation_id: string;
          organization_id: string;
          role: "user" | "assistant";
          content: string;
          tool_calls: Json | null;
          tool_results: Json | null;
          tokens_used: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          organization_id: string;
          role: "user" | "assistant";
          content: string;
          tool_calls?: Json | null;
          tool_results?: Json | null;
          tokens_used?: number;
          created_at?: string;
        };
        Update: {
          content?: string;
          tool_calls?: Json | null;
          tool_results?: Json | null;
          tokens_used?: number;
        };
        Relationships: [];
      };
      copilot_memory: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string;
          type: "business_details" | "product_info" | "target_audience" | "brand_voice" | "custom";
          title: string;
          content: string;
          source: "manual" | "website" | "file" | null;
          source_url: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          user_id: string;
          type: "business_details" | "product_info" | "target_audience" | "brand_voice" | "custom";
          title: string;
          content: string;
          source?: "manual" | "website" | "file" | null;
          source_url?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          type?: "business_details" | "product_info" | "target_audience" | "brand_voice" | "custom";
          title?: string;
          content?: string;
          source?: "manual" | "website" | "file" | null;
          source_url?: string | null;
          is_active?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      copilot_tasks: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string;
          title: string;
          prompt: string;
          schedule: "daily" | "weekly" | "monthly" | "custom";
          cron_expression: string | null;
          is_active: boolean;
          last_run_at: string | null;
          next_run_at: string | null;
          run_count: number;
          last_result: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          user_id: string;
          title: string;
          prompt: string;
          schedule: "daily" | "weekly" | "monthly" | "custom";
          cron_expression?: string | null;
          is_active?: boolean;
          last_run_at?: string | null;
          next_run_at?: string | null;
          run_count?: number;
          last_result?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          title?: string;
          prompt?: string;
          schedule?: "daily" | "weekly" | "monthly" | "custom";
          cron_expression?: string | null;
          is_active?: boolean;
          last_run_at?: string | null;
          next_run_at?: string | null;
          run_count?: number;
          last_result?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      tracking_scripts: {
        Row: {
          id: string;
          organization_id: string;
          domain: string;
          script_key: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          domain: string;
          script_key?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          domain?: string;
          script_key?: string;
          is_active?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      website_visitors: {
        Row: {
          id: string;
          organization_id: string;
          script_id: string | null;
          session_id: string | null;
          ip_address: string | null;
          company_name: string | null;
          company_domain: string | null;
          city: string | null;
          region: string | null;
          country: string | null;
          country_code: string | null;
          first_seen: string;
          last_seen: string;
          visit_count: number;
          page_count: number;
          total_duration: number;
          status: "new" | "returning" | "hot" | "converted" | "ignored";
          lead_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          script_id?: string | null;
          session_id?: string | null;
          ip_address?: string | null;
          company_name?: string | null;
          company_domain?: string | null;
          city?: string | null;
          region?: string | null;
          country?: string | null;
          country_code?: string | null;
          first_seen?: string;
          last_seen?: string;
          visit_count?: number;
          page_count?: number;
          total_duration?: number;
          status?: "new" | "returning" | "hot" | "converted" | "ignored";
          lead_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          script_id?: string | null;
          session_id?: string | null;
          ip_address?: string | null;
          company_name?: string | null;
          company_domain?: string | null;
          city?: string | null;
          region?: string | null;
          country?: string | null;
          country_code?: string | null;
          first_seen?: string;
          last_seen?: string;
          visit_count?: number;
          page_count?: number;
          total_duration?: number;
          status?: "new" | "returning" | "hot" | "converted" | "ignored";
          lead_id?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      website_visits: {
        Row: {
          id: string;
          visitor_id: string;
          organization_id: string;
          page_url: string;
          page_title: string | null;
          referrer: string | null;
          duration: number | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          visitor_id: string;
          organization_id: string;
          page_url: string;
          page_title?: string | null;
          referrer?: string | null;
          duration?: number | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          visitor_id?: string;
          organization_id?: string;
          page_url?: string;
          page_title?: string | null;
          referrer?: string | null;
          duration?: number | null;
          user_agent?: string | null;
        };
        Relationships: [];
      };
      automation_rules: {
        Row: {
          id: string;
          organization_id: string;
          created_by: string | null;
          name: string;
          description: string | null;
          is_active: boolean;
          trigger_type: string;
          trigger_config: Json;
          conditions: Json;
          actions: Json;
          execution_count: number;
          last_executed_at: string | null;
          execution_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          created_by?: string | null;
          name: string;
          description?: string | null;
          is_active?: boolean;
          trigger_type: string;
          trigger_config?: Json;
          conditions?: Json;
          actions?: Json;
          execution_count?: number;
          last_executed_at?: string | null;
          execution_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          created_by?: string | null;
          name?: string;
          description?: string | null;
          is_active?: boolean;
          trigger_type?: string;
          trigger_config?: Json;
          conditions?: Json;
          actions?: Json;
          execution_count?: number;
          last_executed_at?: string | null;
          execution_order?: number;
        };
        Relationships: [];
      };
      automation_executions: {
        Row: {
          id: string;
          rule_id: string;
          lead_id: string | null;
          trigger_type: string;
          trigger_data: Json;
          actions_executed: Json;
          success: boolean;
          error_message: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          rule_id: string;
          lead_id?: string | null;
          trigger_type: string;
          trigger_data?: Json;
          actions_executed?: Json;
          success?: boolean;
          error_message?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          rule_id?: string;
          lead_id?: string | null;
          trigger_type?: string;
          trigger_data?: Json;
          actions_executed?: Json;
          success?: boolean;
          error_message?: string | null;
        };
        Relationships: [];
      };
      custom_fields: {
        Row: {
          id: string;
          organization_id: string;
          entity_type: string;
          field_key: string;
          field_label: string;
          field_type: string;
          options: Json;
          is_merge_field: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          entity_type?: string;
          field_key: string;
          field_label: string;
          field_type?: string;
          options?: Json;
          is_merge_field?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          entity_type?: string;
          field_key?: string;
          field_label?: string;
          field_type?: string;
          options?: Json;
          is_merge_field?: boolean;
        };
        Relationships: [];
      };
      lead_custom_field_values: {
        Row: {
          id: string;
          lead_id: string;
          field_id: string;
          value: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          lead_id: string;
          field_id: string;
          value?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          lead_id?: string;
          field_id?: string;
          value?: string | null;
        };
        Relationships: [];
      };
      campaign_runs: {
        Row: {
          id: string;
          organization_id: string;
          created_by: string | null;
          name: string;
          description: string | null;
          status: string;
          sequence_id: string | null;
          audience_type: string;
          audience_filters: Json;
          audience_lead_ids: string[];
          email_account_ids: string[];
          rotation_strategy: string;
          daily_send_limit: number;
          start_date: string | null;
          schedule_timezone: string;
          schedule_windows: Json;
          total_audience: number;
          total_enrolled: number;
          total_sent: number;
          total_opened: number;
          total_clicked: number;
          total_replied: number;
          total_bounced: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          created_by?: string | null;
          name: string;
          description?: string | null;
          status?: string;
          sequence_id?: string | null;
          audience_type?: string;
          audience_filters?: Json;
          audience_lead_ids?: string[];
          email_account_ids?: string[];
          rotation_strategy?: string;
          daily_send_limit?: number;
          start_date?: string | null;
          schedule_timezone?: string;
          schedule_windows?: Json;
          total_audience?: number;
          total_enrolled?: number;
          total_sent?: number;
          total_opened?: number;
          total_clicked?: number;
          total_replied?: number;
          total_bounced?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          created_by?: string | null;
          name?: string;
          description?: string | null;
          status?: string;
          sequence_id?: string | null;
          audience_type?: string;
          audience_filters?: Json;
          audience_lead_ids?: string[];
          email_account_ids?: string[];
          rotation_strategy?: string;
          daily_send_limit?: number;
          start_date?: string | null;
          schedule_timezone?: string;
          schedule_windows?: Json;
          total_audience?: number;
          total_enrolled?: number;
          total_sent?: number;
          total_opened?: number;
          total_clicked?: number;
          total_replied?: number;
          total_bounced?: number;
        };
        Relationships: [];
      };
      campaign_leads: {
        Row: {
          id: string;
          campaign_id: string;
          lead_id: string;
          enrollment_id: string | null;
          status: string;
          added_at: string;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          lead_id: string;
          enrollment_id?: string | null;
          status?: string;
          added_at?: string;
        };
        Update: {
          id?: string;
          campaign_id?: string;
          lead_id?: string;
          enrollment_id?: string | null;
          status?: string;
        };
        Relationships: [];
      };
      // ============================================================
      // MULTI-CHANNEL: WhatsApp + LinkedIn
      // ============================================================
      whatsapp_accounts: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string;
          phone_number_id: string;
          waba_id: string;
          access_token_encrypted: string;
          display_phone_number: string;
          verified_name: string | null;
          status: string;
          daily_send_limit: number;
          daily_sent_count: number;
          quality_rating: string | null;
          messaging_limit: string | null;
          last_error: string | null;
          webhook_secret: string | null;
          is_default: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          user_id: string;
          phone_number_id: string;
          waba_id: string;
          access_token_encrypted: string;
          display_phone_number: string;
          verified_name?: string | null;
          status?: string;
          daily_send_limit?: number;
          daily_sent_count?: number;
          quality_rating?: string | null;
          messaging_limit?: string | null;
          last_error?: string | null;
          webhook_secret?: string | null;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          phone_number_id?: string;
          waba_id?: string;
          access_token_encrypted?: string;
          display_phone_number?: string;
          verified_name?: string | null;
          status?: string;
          daily_send_limit?: number;
          daily_sent_count?: number;
          quality_rating?: string | null;
          messaging_limit?: string | null;
          last_error?: string | null;
          webhook_secret?: string | null;
          is_default?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      whatsapp_templates: {
        Row: {
          id: string;
          organization_id: string;
          whatsapp_account_id: string;
          meta_template_id: string | null;
          name: string;
          language: string;
          category: string;
          status: string;
          components: Json;
          header_type: string | null;
          body_text: string | null;
          footer_text: string | null;
          buttons: Json | null;
          example_values: Json | null;
          last_synced_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          whatsapp_account_id: string;
          meta_template_id?: string | null;
          name: string;
          language?: string;
          category?: string;
          status?: string;
          components?: Json;
          header_type?: string | null;
          body_text?: string | null;
          footer_text?: string | null;
          buttons?: Json | null;
          example_values?: Json | null;
          last_synced_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          meta_template_id?: string | null;
          name?: string;
          language?: string;
          category?: string;
          status?: string;
          components?: Json;
          header_type?: string | null;
          body_text?: string | null;
          footer_text?: string | null;
          buttons?: Json | null;
          example_values?: Json | null;
          last_synced_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      whatsapp_messages: {
        Row: {
          id: string;
          organization_id: string;
          whatsapp_account_id: string;
          lead_id: string | null;
          enrollment_id: string | null;
          step_id: string | null;
          direction: string;
          message_type: string;
          wa_message_id: string | null;
          template_id: string | null;
          template_params: Json | null;
          body_text: string | null;
          media_url: string | null;
          media_mime_type: string | null;
          media_caption: string | null;
          status: string;
          error_code: string | null;
          error_message: string | null;
          conversation_id: string | null;
          sent_at: string | null;
          delivered_at: string | null;
          read_at: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          whatsapp_account_id: string;
          lead_id?: string | null;
          enrollment_id?: string | null;
          step_id?: string | null;
          direction?: string;
          message_type?: string;
          wa_message_id?: string | null;
          template_id?: string | null;
          template_params?: Json | null;
          body_text?: string | null;
          media_url?: string | null;
          media_mime_type?: string | null;
          media_caption?: string | null;
          status?: string;
          error_code?: string | null;
          error_message?: string | null;
          conversation_id?: string | null;
          sent_at?: string | null;
          delivered_at?: string | null;
          read_at?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          direction?: string;
          message_type?: string;
          wa_message_id?: string | null;
          template_id?: string | null;
          template_params?: Json | null;
          body_text?: string | null;
          media_url?: string | null;
          media_mime_type?: string | null;
          media_caption?: string | null;
          status?: string;
          error_code?: string | null;
          error_message?: string | null;
          conversation_id?: string | null;
          sent_at?: string | null;
          delivered_at?: string | null;
          read_at?: string | null;
          metadata?: Json;
        };
        Relationships: [];
      };
      linkedin_accounts: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string;
          linkedin_id: string | null;
          display_name: string | null;
          profile_url: string | null;
          avatar_url: string | null;
          access_token_encrypted: string;
          refresh_token_encrypted: string | null;
          token_expires_at: string | null;
          scopes: string[] | null;
          status: string;
          daily_connection_requests: number;
          daily_messages_sent: number;
          weekly_connection_requests: number;
          daily_profile_views: number;
          daily_endorsements: number;
          daily_connection_limit: number;
          daily_message_limit: number;
          weekly_connection_limit: number;
          daily_profile_view_limit: number;
          daily_endorsement_limit: number;
          last_error: string | null;
          is_default: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          user_id: string;
          linkedin_id?: string | null;
          display_name?: string | null;
          profile_url?: string | null;
          avatar_url?: string | null;
          access_token_encrypted: string;
          refresh_token_encrypted?: string | null;
          token_expires_at?: string | null;
          scopes?: string[] | null;
          status?: string;
          daily_connection_requests?: number;
          daily_messages_sent?: number;
          weekly_connection_requests?: number;
          daily_profile_views?: number;
          daily_endorsements?: number;
          daily_connection_limit?: number;
          daily_message_limit?: number;
          weekly_connection_limit?: number;
          daily_profile_view_limit?: number;
          daily_endorsement_limit?: number;
          last_error?: string | null;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          linkedin_id?: string | null;
          display_name?: string | null;
          profile_url?: string | null;
          avatar_url?: string | null;
          access_token_encrypted?: string;
          refresh_token_encrypted?: string | null;
          token_expires_at?: string | null;
          scopes?: string[] | null;
          status?: string;
          daily_connection_requests?: number;
          daily_messages_sent?: number;
          weekly_connection_requests?: number;
          daily_profile_views?: number;
          daily_endorsements?: number;
          daily_connection_limit?: number;
          daily_message_limit?: number;
          weekly_connection_limit?: number;
          daily_profile_view_limit?: number;
          daily_endorsement_limit?: number;
          last_error?: string | null;
          is_default?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      linkedin_actions: {
        Row: {
          id: string;
          organization_id: string;
          linkedin_account_id: string;
          lead_id: string | null;
          enrollment_id: string | null;
          step_id: string | null;
          action_type: string;
          status: string;
          connection_note: string | null;
          message_body: string | null;
          target_linkedin_url: string | null;
          target_linkedin_id: string | null;
          skill_name: string | null;
          response_body: string | null;
          responded_at: string | null;
          error_message: string | null;
          sent_at: string | null;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          linkedin_account_id: string;
          lead_id?: string | null;
          enrollment_id?: string | null;
          step_id?: string | null;
          action_type: string;
          status?: string;
          connection_note?: string | null;
          message_body?: string | null;
          target_linkedin_url?: string | null;
          target_linkedin_id?: string | null;
          skill_name?: string | null;
          response_body?: string | null;
          responded_at?: string | null;
          error_message?: string | null;
          sent_at?: string | null;
          metadata?: Json;
          created_at?: string;
        };
        Update: {
          action_type?: string;
          status?: string;
          connection_note?: string | null;
          message_body?: string | null;
          target_linkedin_url?: string | null;
          target_linkedin_id?: string | null;
          skill_name?: string | null;
          response_body?: string | null;
          responded_at?: string | null;
          error_message?: string | null;
          sent_at?: string | null;
          metadata?: Json;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      customer_status: "active" | "pending" | "inactive";
      customer_plan: "enterprise" | "pro" | "starter" | "free";
      lead_status: "hot" | "warm" | "cold";
      lead_source:
        | "Website"
        | "Referral"
        | "LinkedIn"
        | "Event"
        | "Google Ads"
        | "Cold Call";
      deal_stage:
        | "discovery"
        | "proposal"
        | "negotiation"
        | "closed_won"
        | "closed_lost";
      activity_type: "call" | "meeting" | "task" | "email" | "note";
      activity_status: "completed" | "scheduled" | "pending" | "cancelled";
      related_entity_type: "deal" | "customer" | "lead";
      sequence_status: "draft" | "active" | "paused" | "archived";
      enrollment_status: "active" | "paused" | "completed" | "replied" | "bounced" | "unsubscribed";
      email_provider: "gmail" | "microsoft" | "custom_imap";
      email_account_status: "active" | "disconnected" | "error" | "warming_up";
      email_direction: "inbound" | "outbound";
      email_message_status: "draft" | "queued" | "sending" | "sent" | "delivered" | "opened" | "clicked" | "replied" | "bounced" | "failed";
      tracking_event_type: "sent" | "delivered" | "opened" | "clicked" | "bounced" | "complaint" | "unsubscribed";
    };
    CompositeTypes: Record<string, never>;
  };
};

// Convenience type aliases
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type InsertTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type UpdateTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
export type Enums<T extends keyof Database["public"]["Enums"]> =
  Database["public"]["Enums"][T];
