import { defineView, ViewSortDirection, ViewType } from 'twenty-sdk/define';

import {
  WEBSITE_VISITS_VIEW_ID,
  WEBSITE_VISIT_OBJECT_ID,
  WV_AD_CLICK_FIELD_ID,
  WV_COMPANY_FIELD_ID,
  WV_COMPANY_NAME_FIELD_ID,
  WV_COUNTRY_FIELD_ID,
  WV_ENRICH_STATUS_FIELD_ID,
  WV_INTENT_SCORE_FIELD_ID,
  WV_PAGE_VIEWS_FIELD_ID,
  WV_PERSON_FIELD_ID,
  WV_RECENT_PAGES_FIELD_ID,
  WV_REFERRER_FIELD_ID,
  WV_UTM_CAMPAIGN_FIELD_ID,
  WV_UTM_SOURCE_FIELD_ID,
  WV_VIEW_F_AD_CLICK_ID,
  WV_VIEW_F_CAMPAIGN_ID,
  WV_VIEW_F_COMPANY_ID,
  WV_VIEW_F_COMPANY_NAME_ID,
  WV_VIEW_F_DOMAIN_ID,
  WV_VIEW_F_ENRICH_STATUS_ID,
  WV_VIEW_F_INTENT_ID,
  WV_VIEW_F_LOCATION_ID,
  WV_VIEW_F_PAGE_VIEWS_ID,
  WV_VIEW_F_PERSON_ID,
  WV_VIEW_F_RECENT_PAGES_ID,
  WV_VIEW_F_REFERRER_ID,
  WV_VIEW_F_SOURCE_ID,
  WV_VIEW_F_URL_ID,
  WV_VIEW_F_VISITED_AT_ID,
  WV_VIEW_F_VISITOR_ID,
  WV_VIEW_SORT_ID,
  WV_COMPANY_DOMAIN_FIELD_ID,
  WV_URL_FIELD_ID,
  WV_VISITED_AT_FIELD_ID,
  WV_VISITOR_ID_FIELD_ID,
} from 'src/constants/insights-ids';

// Most recent visitors first, with who they are, how warm and where from.
const columns: [viewFieldId: string, fieldId: string, size: number][] = [
  [WV_VIEW_F_VISITOR_ID, WV_VISITOR_ID_FIELD_ID, 140],
  [WV_VIEW_F_COMPANY_ID, WV_COMPANY_FIELD_ID, 170],
  [WV_VIEW_F_COMPANY_NAME_ID, WV_COMPANY_NAME_FIELD_ID, 170],
  [WV_VIEW_F_INTENT_ID, WV_INTENT_SCORE_FIELD_ID, 100],
  [WV_VIEW_F_PERSON_ID, WV_PERSON_FIELD_ID, 160],
  [WV_VIEW_F_RECENT_PAGES_ID, WV_RECENT_PAGES_FIELD_ID, 240],
  [WV_VIEW_F_PAGE_VIEWS_ID, WV_PAGE_VIEWS_FIELD_ID, 100],
  [WV_VIEW_F_AD_CLICK_ID, WV_AD_CLICK_FIELD_ID, 100],
  [WV_VIEW_F_SOURCE_ID, WV_UTM_SOURCE_FIELD_ID, 120],
  [WV_VIEW_F_CAMPAIGN_ID, WV_UTM_CAMPAIGN_FIELD_ID, 140],
  [WV_VIEW_F_REFERRER_ID, WV_REFERRER_FIELD_ID, 200],
  [WV_VIEW_F_LOCATION_ID, WV_COUNTRY_FIELD_ID, 90],
  [WV_VIEW_F_ENRICH_STATUS_ID, WV_ENRICH_STATUS_FIELD_ID, 130],
  [WV_VIEW_F_DOMAIN_ID, WV_COMPANY_DOMAIN_FIELD_ID, 150],
  [WV_VIEW_F_URL_ID, WV_URL_FIELD_ID, 240],
  [WV_VIEW_F_VISITED_AT_ID, WV_VISITED_AT_FIELD_ID, 150],
];

export default defineView({
  universalIdentifier: WEBSITE_VISITS_VIEW_ID,
  name: 'Website Visitors',
  objectUniversalIdentifier: WEBSITE_VISIT_OBJECT_ID,
  type: ViewType.TABLE,
  icon: 'IconWorldWww',
  position: 0,
  fields: columns.map(([universalIdentifier, fieldMetadataUniversalIdentifier, size], position) => ({
    universalIdentifier,
    fieldMetadataUniversalIdentifier,
    position,
    size,
  })),
  sorts: [
    {
      universalIdentifier: WV_VIEW_SORT_ID,
      fieldMetadataUniversalIdentifier: WV_VISITED_AT_FIELD_ID,
      direction: ViewSortDirection.DESC,
    },
  ],
});
