"use client";
export {
  // Navigation & Layout
  SidebarSimpleIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  ArrowLeftIcon,
  // Dashboard
  GaugeIcon,
  UsersIcon,
  UsersThreeIcon,
  UserIcon,
  FunnelIcon,
  CurrencyDollarIcon,
  PulseIcon,
  GearIcon,
  SparkleIcon,
  FadersIcon,
  ActivityIcon,
  // Actions
  CalendarBlankIcon,
  MagnifyingGlassIcon,
  BellIcon,
  PlusIcon,
  ExportIcon,
  DownloadSimpleIcon as DownloadIcon,
  DotsThreeVerticalIcon,
  DotsThreeIcon,
  XIcon,
  EyeIcon,
  PencilSimpleIcon,
  EnvelopeIcon,
  TrashIcon,
  UploadSimpleIcon,
  ImageIcon,
  // Arrows
  ArrowUpIcon,
  ArrowDownIcon,
  ArrowRightIcon,
  ArrowElbowDownLeftIcon,
  ArrowUpRightIcon,
  // Status
  CheckIcon,
  CheckCircleIcon,
  TrophyIcon,
  WarningIcon,
  CircleNotchIcon,
  // Communication & Activity
  PhoneIcon,
  VideoIcon,
  NoteIcon,
  FileTextIcon,
  ClockIcon,
  // Sentiment
  ThumbsUpIcon,
  ThumbsDownIcon,
  MinusCircleIcon,
} from "@phosphor-icons/react";
