"use client";
export {
  // Navigation & Layout
  ListIcon,
  SidebarSimpleIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  ArrowLeftIcon,
  // Dashboard
  GaugeIcon,
  UsersIcon,
  UsersThreeIcon,
  UserIcon,
  FunnelIcon,
  CurrencyDollarIcon,
  PulseIcon,
  GearIcon,
  SparkleIcon,
  FadersIcon,
  ActivityIcon,
  // Actions
  CalendarBlankIcon,
  MagnifyingGlassIcon,
  BellIcon,
  PlusIcon,
  ExportIcon,
  DownloadSimpleIcon as DownloadIcon,
  DotsThreeVerticalIcon,
  DotsThreeIcon,
  XIcon,
  EyeIcon,
  EyeSlashIcon,
  PencilSimpleIcon,
  EnvelopeIcon,
  TrashIcon,
  UploadSimpleIcon,
  ImageIcon,
  UploadIcon,
  // Arrows
  ArrowUpIcon,
  ArrowDownIcon,
  ArrowRightIcon,
  ArrowElbowDownLeftIcon,
  ArrowUpRightIcon,
  // Status
  CheckIcon,
  CheckCircleIcon,
  TrophyIcon,
  WarningIcon,
  CircleNotchIcon,
  // Communication & Activity
  PhoneIcon,
  VideoIcon,
  NoteIcon,
  FileTextIcon,
  ClockIcon,
  MonitorIcon,
  // Sentiment
  ThumbsUpIcon,
  ThumbsDownIcon,
  MinusCircleIcon,
  // Settings
  LockIcon,
  GearSixIcon,
  PuzzlePieceIcon,
  CreditCardIcon,
  // Devices
  DeviceMobileIcon,
  // Billing
  StarIcon,
  LightningIcon,
  // ICP
  CrosshairIcon,
  // Competitors
  GlobeIcon,
  ShieldIcon,
  // Analytics
  ChartBarIcon,
  TrendUpIcon,
  // Proposals
  ScrollIcon,
  // Contacts
  AddressBookIcon,
  // AI
  RobotIcon,
  BrainIcon,
  ChatCircleIcon,
  PaperPlaneTiltIcon,
  CursorClickIcon,
  CopyIcon,
  FireIcon,
  MapPinIcon,
  ArrowClockwiseIcon as ArrowPathIcon,
  // Email
  TrayIcon,
  PlugsConnectedIcon,
  GoogleLogoIcon,
  MicrosoftOutlookLogoIcon,
  HardDrivesIcon,
  CircleIcon,
  ArrowsClockwiseIcon,
  DotsSixVerticalIcon,
  WarningCircleIcon,
  FunnelSimpleIcon,
  ArrowSquareOutIcon,
  TrophyIcon as TrophyFilledIcon,
} from "@phosphor-icons/react";
