import { defineObject, FieldType, RelationType } from 'twenty-sdk/define';

import {
  MAILBOX_AUTH_TYPE_UID,
  MAILBOX_BOUNCE_RATE_UID,
  MAILBOX_CONNECTION_ID_UID,
  MAILBOX_CREDENTIAL_CIPHERTEXT_UID,
  MAILBOX_DAILY_SEND_LIMIT_UID,
  MAILBOX_DISPLAY_NAME_UID,
  MAILBOX_EMAIL_UID,
  MAILBOX_HEALTH_SCORE_UID,
  MAILBOX_IMAP_HOST_UID,
  MAILBOX_IMAP_PORT_UID,
  MAILBOX_LAST_ERROR_UID,
  MAILBOX_LAST_SENT_AT_UID,
  MAILBOX_OBJECT_UID,
  MAILBOX_PROVIDER_UID,
  MAILBOX_RECEIVED_WARMUP_MESSAGES_UID,
  MAILBOX_SENT_TODAY_UID,
  MAILBOX_SENT_WARMUP_MESSAGES_UID,
  MAILBOX_SMTP_HOST_UID,
  MAILBOX_SMTP_PORT_UID,
  MAILBOX_SMTP_SECURE_UID,
  MAILBOX_SPAM_PLACEMENT_RATE_UID,
  MAILBOX_STATUS_UID,
  MAILBOX_USERNAME_UID,
  MAILBOX_WARMUP_DAY_UID,
  MAILBOX_WARMUP_ENABLED_UID,
  MAILBOX_WARMUP_SENT_TODAY_UID,
  MAILBOX_WARMUP_STAGE_UID,
  MAILBOX_WARMUP_STARTED_AT_UID,
  WARMUP_MESSAGE_FROM_MAILBOX_UID,
  WARMUP_MESSAGE_OBJECT_UID,
  WARMUP_MESSAGE_TO_MAILBOX_UID,
} from 'src/constants/mailbox-ids';
import { MAILBOX_AUTH_TYPES, MAILBOX_PROVIDERS, MAILBOX_STATUSES, WARMUP_STAGES } from 'src/gtm/mailbox/values';

// A sending mailbox. Sequences send through these; the warmup crons keep
// their reputation up. The password is never stored here in plain text: set
// it through the setMailboxCredential route, which seals it with
// MAILBOX_ENCRYPTION_KEY into credentialCiphertext.
export default defineObject({
  universalIdentifier: MAILBOX_OBJECT_UID,
  nameSingular: 'mailbox',
  namePlural: 'mailboxes',
  labelSingular: 'Mailbox',
  labelPlural: 'Mailboxes',
  description: 'Sending mailboxes with self-built warmup, send caps and health',
  icon: 'IconMailbox',
  labelIdentifierFieldMetadataUniversalIdentifier: MAILBOX_EMAIL_UID,
  fields: [
    { universalIdentifier: MAILBOX_EMAIL_UID, type: FieldType.TEXT, name: 'email', label: 'Email', icon: 'IconMail', isUnique: true },
    { universalIdentifier: MAILBOX_DISPLAY_NAME_UID, type: FieldType.TEXT, name: 'displayName', label: 'Sender name', icon: 'IconUser' },
    {
      universalIdentifier: MAILBOX_PROVIDER_UID,
      type: FieldType.SELECT,
      name: 'provider',
      label: 'Provider',
      icon: 'IconBuildingStore',
      options: MAILBOX_PROVIDERS.map((option, position) => ({ ...option, position })),
      defaultValue: "'OTHER'",
    },
    { universalIdentifier: MAILBOX_SMTP_HOST_UID, type: FieldType.TEXT, name: 'smtpHost', label: 'SMTP host', icon: 'IconServer' },
    { universalIdentifier: MAILBOX_SMTP_PORT_UID, type: FieldType.NUMBER, name: 'smtpPort', label: 'SMTP port', icon: 'IconPlug' },
    { universalIdentifier: MAILBOX_SMTP_SECURE_UID, type: FieldType.BOOLEAN, name: 'smtpSecure', label: 'SMTP implicit TLS', icon: 'IconLock', description: 'On for port 465; off to use STARTTLS (port 587)' },
    { universalIdentifier: MAILBOX_IMAP_HOST_UID, type: FieldType.TEXT, name: 'imapHost', label: 'IMAP host', icon: 'IconServer' },
    { universalIdentifier: MAILBOX_IMAP_PORT_UID, type: FieldType.NUMBER, name: 'imapPort', label: 'IMAP port', icon: 'IconPlug' },
    { universalIdentifier: MAILBOX_USERNAME_UID, type: FieldType.TEXT, name: 'username', label: 'Login username', icon: 'IconUserCircle', description: 'Defaults to the email address' },
    {
      universalIdentifier: MAILBOX_AUTH_TYPE_UID,
      type: FieldType.SELECT,
      name: 'authType',
      label: 'Sign-in',
      icon: 'IconShieldLock',
      description: 'App password, OAuth connection, or Google Workspace domain-wide delegation (no password stored)',
      options: MAILBOX_AUTH_TYPES.map((option, position) => ({ ...option, position })),
      defaultValue: "'PASSWORD'",
    },
    {
      universalIdentifier: MAILBOX_CREDENTIAL_CIPHERTEXT_UID,
      type: FieldType.TEXT,
      name: 'credentialCiphertext',
      label: 'Credential (encrypted)',
      icon: 'IconKey',
      description: 'AES-256-GCM sealed app password. Written only by the setMailboxCredential route.',
      isUIEditable: false,
    },
    {
      universalIdentifier: MAILBOX_CONNECTION_ID_UID,
      type: FieldType.TEXT,
      name: 'connectionId',
      label: 'OAuth connection id',
      icon: 'IconPlugConnected',
      description: 'Optional Google/Microsoft app connection used instead of a password',
    },
    {
      universalIdentifier: MAILBOX_STATUS_UID,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      icon: 'IconActivity',
      options: MAILBOX_STATUSES.map((option, position) => ({ ...option, position })),
      defaultValue: "'WARMING'",
    },
    { universalIdentifier: MAILBOX_WARMUP_ENABLED_UID, type: FieldType.BOOLEAN, name: 'warmupEnabled', label: 'Warmup on', icon: 'IconFlame', defaultValue: true },
    { universalIdentifier: MAILBOX_WARMUP_STARTED_AT_UID, type: FieldType.DATE_TIME, name: 'warmupStartedAt', label: 'Warmup started', icon: 'IconCalendar' },
    { universalIdentifier: MAILBOX_WARMUP_DAY_UID, type: FieldType.NUMBER, name: 'warmupDay', label: 'Warmup day', icon: 'IconCalendarStats', defaultValue: 0 },
    {
      universalIdentifier: MAILBOX_WARMUP_STAGE_UID,
      type: FieldType.SELECT,
      name: 'warmupStage',
      label: 'Warmup stage',
      icon: 'IconStairsUp',
      options: WARMUP_STAGES.map((option, position) => ({ ...option, position })),
      defaultValue: "'STARTING'",
    },
    { universalIdentifier: MAILBOX_DAILY_SEND_LIMIT_UID, type: FieldType.NUMBER, name: 'dailySendLimit', label: 'Daily send cap', icon: 'IconGauge', defaultValue: 0 },
    { universalIdentifier: MAILBOX_SENT_TODAY_UID, type: FieldType.NUMBER, name: 'sentToday', label: 'Sent today', icon: 'IconSend', defaultValue: 0, description: 'Sequence emails sent today (counts against the cap)' },
    { universalIdentifier: MAILBOX_WARMUP_SENT_TODAY_UID, type: FieldType.NUMBER, name: 'warmupSentToday', label: 'Warmup sent today', icon: 'IconFlame', defaultValue: 0 },
    { universalIdentifier: MAILBOX_LAST_SENT_AT_UID, type: FieldType.DATE_TIME, name: 'lastSentAt', label: 'Last sequence send', icon: 'IconClock' },
    { universalIdentifier: MAILBOX_SPAM_PLACEMENT_RATE_UID, type: FieldType.NUMBER, name: 'spamPlacementRate', label: 'Spam placement', icon: 'IconAlertTriangle', defaultValue: 0, description: 'Share of warmup emails that landed in spam, last 14 days (0..1)' },
    { universalIdentifier: MAILBOX_BOUNCE_RATE_UID, type: FieldType.NUMBER, name: 'bounceRate', label: 'Bounce rate', icon: 'IconArrowBackUp', defaultValue: 0, description: 'Share of warmup emails rejected, last 14 days (0..1)' },
    { universalIdentifier: MAILBOX_HEALTH_SCORE_UID, type: FieldType.NUMBER, name: 'healthScore', label: 'Health', icon: 'IconHeartbeat', defaultValue: 100, description: '0..100 from spam placement, bounces and errors' },
    { universalIdentifier: MAILBOX_LAST_ERROR_UID, type: FieldType.TEXT, name: 'lastError', label: 'Last error', icon: 'IconAlertCircle' },
    {
      universalIdentifier: MAILBOX_SENT_WARMUP_MESSAGES_UID,
      type: FieldType.RELATION,
      name: 'sentWarmupMessages',
      label: 'Warmup sent',
      icon: 'IconSend',
      relationTargetObjectMetadataUniversalIdentifier: WARMUP_MESSAGE_OBJECT_UID,
      relationTargetFieldMetadataUniversalIdentifier: WARMUP_MESSAGE_FROM_MAILBOX_UID,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
    {
      universalIdentifier: MAILBOX_RECEIVED_WARMUP_MESSAGES_UID,
      type: FieldType.RELATION,
      name: 'receivedWarmupMessages',
      label: 'Warmup received',
      icon: 'IconInbox',
      relationTargetObjectMetadataUniversalIdentifier: WARMUP_MESSAGE_OBJECT_UID,
      relationTargetFieldMetadataUniversalIdentifier: WARMUP_MESSAGE_TO_MAILBOX_UID,
      universalSettings: { relationType: RelationType.ONE_TO_MANY },
    },
  ],
});
